---

version: "3"
services:
  baseplate:
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes:
      - ".:/src"
    links:
      - "cassandra"
      - "memcached"
      - "redis"
      - "zookeeper"
      - "redis-cluster-node-0"
      - "redis-cluster-node-1"
      - "redis-cluster-node-2"

  cassandra:
    image: "cassandra:3.11"
    environment:
      HEAP_NEWSIZE: 128M
      MAX_HEAP_SIZE: 256M
  memcached:
    image: "memcached:1.5.6"
  redis:
    image: "redis:4.0.9"
  zookeeper:
    image: "zookeeper:3.4.10"
  redis-cluster-node-0:
    image: docker.io/bitnami/redis-cluster:6.2-debian-10
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2'
  redis-cluster-node-1:
    image: docker.io/bitnami/redis-cluster:6.2-debian-10
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2'
  redis-cluster-node-2:
    image: docker.io/bitnami/redis-cluster:6.2-debian-10
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2'
 redis-cluster-init:
    image: docker.io/bitnami/redis-cluster:6.2-debian-10
    depends_on:
      - redis-cluster-node-0
      - redis-cluster-node-1
      - redis-cluster-node-2
    environment:
      - 'REDISCLI_AUTH='
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2'
      - 'REDIS_CLUSTER_CREATOR=yes'
